// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: api/service/v1/service.proto

package v1

import (
	v12 "4clabs-server/api/auth/v1"
	v1 "4clabs-server/api/nft/v1"
	v11 "4clabs-server/api/tickets/v1"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NftClient is the client API for Nft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NftClient interface {
	// commic works
	ListComicWorks(ctx context.Context, in *v1.ListComicWorkRequest, opts ...grpc.CallOption) (*v1.ListComicWorkResponse, error)
	CreateComic(ctx context.Context, in *v1.ComicCreateRequest, opts ...grpc.CallOption) (*v1.ComicCreateResponse, error)
	// register nft
	RegisterNft(ctx context.Context, in *v1.RegisterNftRequest, opts ...grpc.CallOption) (*v1.RegisterNftResponse, error)
	// register nfts
	ListRegsiterNfts(ctx context.Context, in *v1.ListRegisterNftRequest, opts ...grpc.CallOption) (*v1.ListRegisterNftResponse, error)
	// ticket WL
	InTicketsWLRequest(ctx context.Context, in *v11.CanMintRequest, opts ...grpc.CallOption) (*v11.CantMintResponse, error)
	// 签名登录
	SignToLogin(ctx context.Context, in *v12.VerifySignToLoginSignRequest, opts ...grpc.CallOption) (*v12.VerifySignToLoginSighResponse, error)
	// 拉取地址对应的nonce
	FetchNonce(ctx context.Context, in *v12.FetchSignMessageRequest, opts ...grpc.CallOption) (*v12.FetchSignMessageResponse, error)
	// 地址下nft列表
	GetAddressNfts(ctx context.Context, in *v1.GetAddressNftsRequest, opts ...grpc.CallOption) (*v1.GetAddressNftResponse, error)
	// nft详情页
	GetNftDetail(ctx context.Context, in *v1.GetNftDetailRequest, opts ...grpc.CallOption) (*v1.GetNftDetailResponse, error)
	// 二创NFT列表
	GetComicNftList(ctx context.Context, in *v1.ListComicNftRequest, opts ...grpc.CallOption) (*v1.ListComicNftResponse, error)
	// register nft
	NftPurchase(ctx context.Context, in *v1.PurchaseComicNftRequest, opts ...grpc.CallOption) (*v1.PurchaseComicNftResponse, error)
}

type nftClient struct {
	cc grpc.ClientConnInterface
}

func NewNftClient(cc grpc.ClientConnInterface) NftClient {
	return &nftClient{cc}
}

func (c *nftClient) ListComicWorks(ctx context.Context, in *v1.ListComicWorkRequest, opts ...grpc.CallOption) (*v1.ListComicWorkResponse, error) {
	out := new(v1.ListComicWorkResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/ListComicWorks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) CreateComic(ctx context.Context, in *v1.ComicCreateRequest, opts ...grpc.CallOption) (*v1.ComicCreateResponse, error) {
	out := new(v1.ComicCreateResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/CreateComic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) RegisterNft(ctx context.Context, in *v1.RegisterNftRequest, opts ...grpc.CallOption) (*v1.RegisterNftResponse, error) {
	out := new(v1.RegisterNftResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/RegisterNft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) ListRegsiterNfts(ctx context.Context, in *v1.ListRegisterNftRequest, opts ...grpc.CallOption) (*v1.ListRegisterNftResponse, error) {
	out := new(v1.ListRegisterNftResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/ListRegsiterNfts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) InTicketsWLRequest(ctx context.Context, in *v11.CanMintRequest, opts ...grpc.CallOption) (*v11.CantMintResponse, error) {
	out := new(v11.CantMintResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/InTicketsWLRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) SignToLogin(ctx context.Context, in *v12.VerifySignToLoginSignRequest, opts ...grpc.CallOption) (*v12.VerifySignToLoginSighResponse, error) {
	out := new(v12.VerifySignToLoginSighResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/SignToLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) FetchNonce(ctx context.Context, in *v12.FetchSignMessageRequest, opts ...grpc.CallOption) (*v12.FetchSignMessageResponse, error) {
	out := new(v12.FetchSignMessageResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/FetchNonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) GetAddressNfts(ctx context.Context, in *v1.GetAddressNftsRequest, opts ...grpc.CallOption) (*v1.GetAddressNftResponse, error) {
	out := new(v1.GetAddressNftResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/GetAddressNfts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) GetNftDetail(ctx context.Context, in *v1.GetNftDetailRequest, opts ...grpc.CallOption) (*v1.GetNftDetailResponse, error) {
	out := new(v1.GetNftDetailResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/GetNftDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) GetComicNftList(ctx context.Context, in *v1.ListComicNftRequest, opts ...grpc.CallOption) (*v1.ListComicNftResponse, error) {
	out := new(v1.ListComicNftResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/GetComicNftList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) NftPurchase(ctx context.Context, in *v1.PurchaseComicNftRequest, opts ...grpc.CallOption) (*v1.PurchaseComicNftResponse, error) {
	out := new(v1.PurchaseComicNftResponse)
	err := c.cc.Invoke(ctx, "/api.service.v1.Nft/NftPurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NftServer is the server API for Nft service.
// All implementations must embed UnimplementedNftServer
// for forward compatibility
type NftServer interface {
	// commic works
	ListComicWorks(context.Context, *v1.ListComicWorkRequest) (*v1.ListComicWorkResponse, error)
	CreateComic(context.Context, *v1.ComicCreateRequest) (*v1.ComicCreateResponse, error)
	// register nft
	RegisterNft(context.Context, *v1.RegisterNftRequest) (*v1.RegisterNftResponse, error)
	// register nfts
	ListRegsiterNfts(context.Context, *v1.ListRegisterNftRequest) (*v1.ListRegisterNftResponse, error)
	// ticket WL
	InTicketsWLRequest(context.Context, *v11.CanMintRequest) (*v11.CantMintResponse, error)
	// 签名登录
	SignToLogin(context.Context, *v12.VerifySignToLoginSignRequest) (*v12.VerifySignToLoginSighResponse, error)
	// 拉取地址对应的nonce
	FetchNonce(context.Context, *v12.FetchSignMessageRequest) (*v12.FetchSignMessageResponse, error)
	// 地址下nft列表
	GetAddressNfts(context.Context, *v1.GetAddressNftsRequest) (*v1.GetAddressNftResponse, error)
	// nft详情页
	GetNftDetail(context.Context, *v1.GetNftDetailRequest) (*v1.GetNftDetailResponse, error)
	// 二创NFT列表
	GetComicNftList(context.Context, *v1.ListComicNftRequest) (*v1.ListComicNftResponse, error)
	// register nft
	NftPurchase(context.Context, *v1.PurchaseComicNftRequest) (*v1.PurchaseComicNftResponse, error)
	mustEmbedUnimplementedNftServer()
}

// UnimplementedNftServer must be embedded to have forward compatible implementations.
type UnimplementedNftServer struct {
}

func (UnimplementedNftServer) ListComicWorks(context.Context, *v1.ListComicWorkRequest) (*v1.ListComicWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComicWorks not implemented")
}
func (UnimplementedNftServer) CreateComic(context.Context, *v1.ComicCreateRequest) (*v1.ComicCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComic not implemented")
}
func (UnimplementedNftServer) RegisterNft(context.Context, *v1.RegisterNftRequest) (*v1.RegisterNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNft not implemented")
}
func (UnimplementedNftServer) ListRegsiterNfts(context.Context, *v1.ListRegisterNftRequest) (*v1.ListRegisterNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRegsiterNfts not implemented")
}
func (UnimplementedNftServer) InTicketsWLRequest(context.Context, *v11.CanMintRequest) (*v11.CantMintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InTicketsWLRequest not implemented")
}
func (UnimplementedNftServer) SignToLogin(context.Context, *v12.VerifySignToLoginSignRequest) (*v12.VerifySignToLoginSighResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignToLogin not implemented")
}
func (UnimplementedNftServer) FetchNonce(context.Context, *v12.FetchSignMessageRequest) (*v12.FetchSignMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchNonce not implemented")
}
func (UnimplementedNftServer) GetAddressNfts(context.Context, *v1.GetAddressNftsRequest) (*v1.GetAddressNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressNfts not implemented")
}
func (UnimplementedNftServer) GetNftDetail(context.Context, *v1.GetNftDetailRequest) (*v1.GetNftDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNftDetail not implemented")
}
func (UnimplementedNftServer) GetComicNftList(context.Context, *v1.ListComicNftRequest) (*v1.ListComicNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComicNftList not implemented")
}
func (UnimplementedNftServer) NftPurchase(context.Context, *v1.PurchaseComicNftRequest) (*v1.PurchaseComicNftResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftPurchase not implemented")
}
func (UnimplementedNftServer) mustEmbedUnimplementedNftServer() {}

// UnsafeNftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NftServer will
// result in compilation errors.
type UnsafeNftServer interface {
	mustEmbedUnimplementedNftServer()
}

func RegisterNftServer(s grpc.ServiceRegistrar, srv NftServer) {
	s.RegisterService(&Nft_ServiceDesc, srv)
}

func _Nft_ListComicWorks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListComicWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).ListComicWorks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/ListComicWorks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).ListComicWorks(ctx, req.(*v1.ListComicWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_CreateComic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ComicCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).CreateComic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/CreateComic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).CreateComic(ctx, req.(*v1.ComicCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_RegisterNft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.RegisterNftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).RegisterNft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/RegisterNft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).RegisterNft(ctx, req.(*v1.RegisterNftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_ListRegsiterNfts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListRegisterNftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).ListRegsiterNfts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/ListRegsiterNfts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).ListRegsiterNfts(ctx, req.(*v1.ListRegisterNftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_InTicketsWLRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v11.CanMintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).InTicketsWLRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/InTicketsWLRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).InTicketsWLRequest(ctx, req.(*v11.CanMintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_SignToLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.VerifySignToLoginSignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).SignToLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/SignToLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).SignToLogin(ctx, req.(*v12.VerifySignToLoginSignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_FetchNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v12.FetchSignMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).FetchNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/FetchNonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).FetchNonce(ctx, req.(*v12.FetchSignMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_GetAddressNfts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetAddressNftsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).GetAddressNfts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/GetAddressNfts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).GetAddressNfts(ctx, req.(*v1.GetAddressNftsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_GetNftDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetNftDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).GetNftDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/GetNftDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).GetNftDetail(ctx, req.(*v1.GetNftDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_GetComicNftList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListComicNftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).GetComicNftList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/GetComicNftList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).GetComicNftList(ctx, req.(*v1.ListComicNftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_NftPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.PurchaseComicNftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).NftPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.service.v1.Nft/NftPurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).NftPurchase(ctx, req.(*v1.PurchaseComicNftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nft_ServiceDesc is the grpc.ServiceDesc for Nft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.service.v1.Nft",
	HandlerType: (*NftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListComicWorks",
			Handler:    _Nft_ListComicWorks_Handler,
		},
		{
			MethodName: "CreateComic",
			Handler:    _Nft_CreateComic_Handler,
		},
		{
			MethodName: "RegisterNft",
			Handler:    _Nft_RegisterNft_Handler,
		},
		{
			MethodName: "ListRegsiterNfts",
			Handler:    _Nft_ListRegsiterNfts_Handler,
		},
		{
			MethodName: "InTicketsWLRequest",
			Handler:    _Nft_InTicketsWLRequest_Handler,
		},
		{
			MethodName: "SignToLogin",
			Handler:    _Nft_SignToLogin_Handler,
		},
		{
			MethodName: "FetchNonce",
			Handler:    _Nft_FetchNonce_Handler,
		},
		{
			MethodName: "GetAddressNfts",
			Handler:    _Nft_GetAddressNfts_Handler,
		},
		{
			MethodName: "GetNftDetail",
			Handler:    _Nft_GetNftDetail_Handler,
		},
		{
			MethodName: "GetComicNftList",
			Handler:    _Nft_GetComicNftList_Handler,
		},
		{
			MethodName: "NftPurchase",
			Handler:    _Nft_NftPurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service/v1/service.proto",
}
