// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/base/v1/base.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BaseListRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BaseListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BaseListRequestMultiError, or nil if none found.
func (m *BaseListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LastScore

	// no validation rules for Limit

	if len(errors) > 0 {
		return BaseListRequestMultiError(errors)
	}
	return nil
}

// BaseListRequestMultiError is an error wrapping multiple validation errors
// returned by BaseListRequest.ValidateAll() if the designated constraints
// aren't met.
type BaseListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseListRequestMultiError) AllErrors() []error { return m }

// BaseListRequestValidationError is the validation error returned by
// BaseListRequest.Validate if the designated constraints aren't met.
type BaseListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseListRequestValidationError) ErrorName() string { return "BaseListRequestValidationError" }

// Error satisfies the builtin error interface
func (e BaseListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseListRequestValidationError{}

// Validate checks the field values on BaseListResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BaseListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BaseListResponseMultiError, or nil if none found.
func (m *BaseListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for LastScore

	// no validation rules for HasMore

	// no validation rules for Total

	if len(errors) > 0 {
		return BaseListResponseMultiError(errors)
	}
	return nil
}

// BaseListResponseMultiError is an error wrapping multiple validation errors
// returned by BaseListResponse.ValidateAll() if the designated constraints
// aren't met.
type BaseListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseListResponseMultiError) AllErrors() []error { return m }

// BaseListResponseValidationError is the validation error returned by
// BaseListResponse.Validate if the designated constraints aren't met.
type BaseListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseListResponseValidationError) ErrorName() string { return "BaseListResponseValidationError" }

// Error satisfies the builtin error interface
func (e BaseListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseListResponseValidationError{}
