// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameComicsNft = "comics_nfts"

// ComicsNft mapped from table <comics_nfts>
type ComicsNft struct {
	ID       int32  `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	ComicsID string `gorm:"column:comics_id;type:varchar(200);not null" json:"comics_id"`
	Owner    string `gorm:"column:owner;type:varchar(200);not null" json:"owner"`
	Author   string `gorm:"column:author;type:varchar(200);not null" json:"author"`
	Comic    Comic  `gorm:"foreignKey:comics_id" json:"comic"`
}

// TableName ComicsNft's table name
func (*ComicsNft) TableName() string {
	return TableNameComicsNft
}
