// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTicketWl = "ticket_wls"

// TicketWl mapped from table <ticket_wls>
type TicketWl struct {
	ID        int32     `gorm:"column:id;type:int(20) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Address   string    `gorm:"column:address;type:varchar(100);not null" json:"address"`
	Level     int32     `gorm:"column:level;type:int(200) unsigned;not null" json:"level"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName TicketWl's table name
func (*TicketWl) TableName() string {
	return TableNameTicketWl
}
