// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/script/v1/script.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractAddress string `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TokenId         string `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	UserAddress     string `protobuf:"bytes,3,opt,name=user_address,json=userAddress,proto3" json:"user_address,omitempty"`
}

func (x *ScriptRegisterRequest) Reset() {
	*x = ScriptRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_script_v1_script_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRegisterRequest) ProtoMessage() {}

func (x *ScriptRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_script_v1_script_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRegisterRequest.ProtoReflect.Descriptor instead.
func (*ScriptRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_script_v1_script_proto_rawDescGZIP(), []int{0}
}

func (x *ScriptRegisterRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *ScriptRegisterRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *ScriptRegisterRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

type ScriptRegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScriptRegisterResponse) Reset() {
	*x = ScriptRegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_script_v1_script_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptRegisterResponse) ProtoMessage() {}

func (x *ScriptRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_script_v1_script_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptRegisterResponse.ProtoReflect.Descriptor instead.
func (*ScriptRegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_script_v1_script_proto_rawDescGZIP(), []int{1}
}

type ScriptComicWorksCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsIncrement int32 `protobuf:"varint,1,opt,name=isIncrement,proto3" json:"isIncrement,omitempty"` // 0 全量更新，1 增量更新
}

func (x *ScriptComicWorksCreateRequest) Reset() {
	*x = ScriptComicWorksCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_script_v1_script_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptComicWorksCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptComicWorksCreateRequest) ProtoMessage() {}

func (x *ScriptComicWorksCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_script_v1_script_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptComicWorksCreateRequest.ProtoReflect.Descriptor instead.
func (*ScriptComicWorksCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_script_v1_script_proto_rawDescGZIP(), []int{2}
}

func (x *ScriptComicWorksCreateRequest) GetIsIncrement() int32 {
	if x != nil {
		return x.IsIncrement
	}
	return 0
}

type ScriptComicWorksCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScriptComicWorksCreateResponse) Reset() {
	*x = ScriptComicWorksCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_script_v1_script_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptComicWorksCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptComicWorksCreateResponse) ProtoMessage() {}

func (x *ScriptComicWorksCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_script_v1_script_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptComicWorksCreateResponse.ProtoReflect.Descriptor instead.
func (*ScriptComicWorksCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_script_v1_script_proto_rawDescGZIP(), []int{3}
}

type ScriptComicWorksSoldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId int64  `protobuf:"varint,1,opt,name=tokenId,proto3" json:"tokenId,omitempty"`
	To      string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *ScriptComicWorksSoldRequest) Reset() {
	*x = ScriptComicWorksSoldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_script_v1_script_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptComicWorksSoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptComicWorksSoldRequest) ProtoMessage() {}

func (x *ScriptComicWorksSoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_script_v1_script_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptComicWorksSoldRequest.ProtoReflect.Descriptor instead.
func (*ScriptComicWorksSoldRequest) Descriptor() ([]byte, []int) {
	return file_api_script_v1_script_proto_rawDescGZIP(), []int{4}
}

func (x *ScriptComicWorksSoldRequest) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *ScriptComicWorksSoldRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type ScriptComicWorksSoldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ScriptComicWorksSoldResponse) Reset() {
	*x = ScriptComicWorksSoldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_script_v1_script_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScriptComicWorksSoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptComicWorksSoldResponse) ProtoMessage() {}

func (x *ScriptComicWorksSoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_script_v1_script_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptComicWorksSoldResponse.ProtoReflect.Descriptor instead.
func (*ScriptComicWorksSoldResponse) Descriptor() ([]byte, []int) {
	return file_api_script_v1_script_proto_rawDescGZIP(), []int{5}
}

var File_api_script_v1_script_proto protoreflect.FileDescriptor

var file_api_script_v1_script_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x80, 0x01, 0x0a, 0x15, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x41, 0x0a, 0x1d, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x43, 0x6f, 0x6d, 0x69, 0x63,
	0x57, 0x6f, 0x72, 0x6b, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x73, 0x49, 0x6e, 0x63, 0x72, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x1e, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x43, 0x6f,
	0x6d, 0x69, 0x63, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x50, 0x0a, 0x1b, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x43, 0x6f, 0x6d, 0x69, 0x63, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x53, 0x6f, 0x6c, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12,
	0x17, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04,
	0x72, 0x02, 0x10, 0x01, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x1c, 0x53, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x43, 0x6f, 0x6d, 0x69, 0x63, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x53, 0x6f, 0x6c, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x31, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1e, 0x34, 0x63, 0x6c,
	0x61, 0x62, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_script_v1_script_proto_rawDescOnce sync.Once
	file_api_script_v1_script_proto_rawDescData = file_api_script_v1_script_proto_rawDesc
)

func file_api_script_v1_script_proto_rawDescGZIP() []byte {
	file_api_script_v1_script_proto_rawDescOnce.Do(func() {
		file_api_script_v1_script_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_script_v1_script_proto_rawDescData)
	})
	return file_api_script_v1_script_proto_rawDescData
}

var file_api_script_v1_script_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_script_v1_script_proto_goTypes = []interface{}{
	(*ScriptRegisterRequest)(nil),          // 0: api.script.v1.ScriptRegisterRequest
	(*ScriptRegisterResponse)(nil),         // 1: api.script.v1.ScriptRegisterResponse
	(*ScriptComicWorksCreateRequest)(nil),  // 2: api.script.v1.ScriptComicWorksCreateRequest
	(*ScriptComicWorksCreateResponse)(nil), // 3: api.script.v1.ScriptComicWorksCreateResponse
	(*ScriptComicWorksSoldRequest)(nil),    // 4: api.script.v1.ScriptComicWorksSoldRequest
	(*ScriptComicWorksSoldResponse)(nil),   // 5: api.script.v1.ScriptComicWorksSoldResponse
}
var file_api_script_v1_script_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_script_v1_script_proto_init() }
func file_api_script_v1_script_proto_init() {
	if File_api_script_v1_script_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_script_v1_script_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_script_v1_script_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptRegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_script_v1_script_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptComicWorksCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_script_v1_script_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptComicWorksCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_script_v1_script_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptComicWorksSoldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_script_v1_script_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScriptComicWorksSoldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_script_v1_script_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_script_v1_script_proto_goTypes,
		DependencyIndexes: file_api_script_v1_script_proto_depIdxs,
		MessageInfos:      file_api_script_v1_script_proto_msgTypes,
	}.Build()
	File_api_script_v1_script_proto = out.File
	file_api_script_v1_script_proto_rawDesc = nil
	file_api_script_v1_script_proto_goTypes = nil
	file_api_script_v1_script_proto_depIdxs = nil
}
