// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/nft/v1/comic_nft.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on ListComicNftRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListComicNftRequest) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetBaseListRequest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListComicNftRequestValidationError{
				field:  "BaseListRequest",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// ListComicNftRequestValidationError is the validation error returned by
// ListComicNftRequest.Validate if the designated constraints aren't met.
type ListComicNftRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListComicNftRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListComicNftRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListComicNftRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListComicNftRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListComicNftRequestValidationError) ErrorName() string {
	return "ListComicNftRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListComicNftRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListComicNftRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListComicNftRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListComicNftRequestValidationError{}

// Validate checks the field values on ListComicNftResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *ListComicNftResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetBaseListResponse()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListComicNftResponseValidationError{
				field:  "BaseListResponse",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetComicNft() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListComicNftResponseValidationError{
					field:  fmt.Sprintf("ComicNft[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// ListComicNftResponseValidationError is the validation error returned by
// ListComicNftResponse.Validate if the designated constraints aren't met.
type ListComicNftResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListComicNftResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListComicNftResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListComicNftResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListComicNftResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListComicNftResponseValidationError) ErrorName() string {
	return "ListComicNftResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListComicNftResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListComicNftResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListComicNftResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListComicNftResponseValidationError{}

// Validate checks the field values on PurchaseComicNftRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PurchaseComicNftRequest) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for TokenId

	// no validation rules for BuyerAddress

	return nil
}

// PurchaseComicNftRequestValidationError is the validation error returned by
// PurchaseComicNftRequest.Validate if the designated constraints aren't met.
type PurchaseComicNftRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseComicNftRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseComicNftRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseComicNftRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseComicNftRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseComicNftRequestValidationError) ErrorName() string {
	return "PurchaseComicNftRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PurchaseComicNftRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseComicNftRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseComicNftRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseComicNftRequestValidationError{}

// Validate checks the field values on PurchaseComicNftResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *PurchaseComicNftResponse) Validate() error {
	if m == nil {
		return nil
	}

	return nil
}

// PurchaseComicNftResponseValidationError is the validation error returned by
// PurchaseComicNftResponse.Validate if the designated constraints aren't met.
type PurchaseComicNftResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PurchaseComicNftResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PurchaseComicNftResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PurchaseComicNftResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PurchaseComicNftResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PurchaseComicNftResponseValidationError) ErrorName() string {
	return "PurchaseComicNftResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PurchaseComicNftResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPurchaseComicNftResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PurchaseComicNftResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PurchaseComicNftResponseValidationError{}
