// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: api/nft/v1/comic.proto

package v1

import (
	v1 "4clabs-server/api/base/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListComicWorkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseListRequest *v1.BaseListRequest `protobuf:"bytes,1,opt,name=base_list_request,json=baseListRequest,proto3" json:"base_list_request,omitempty"`
	Address         string              `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ListComicWorkRequest) Reset() {
	*x = ListComicWorkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nft_v1_comic_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListComicWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComicWorkRequest) ProtoMessage() {}

func (x *ListComicWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_nft_v1_comic_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComicWorkRequest.ProtoReflect.Descriptor instead.
func (*ListComicWorkRequest) Descriptor() ([]byte, []int) {
	return file_api_nft_v1_comic_proto_rawDescGZIP(), []int{0}
}

func (x *ListComicWorkRequest) GetBaseListRequest() *v1.BaseListRequest {
	if x != nil {
		return x.BaseListRequest
	}
	return nil
}

func (x *ListComicWorkRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListComicWorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseListResponse *v1.BaseListResponse `protobuf:"bytes,1,opt,name=base_list_response,json=baseListResponse,proto3" json:"base_list_response,omitempty"`
	ComicWorks       []*ComicWork         `protobuf:"bytes,2,rep,name=comic_works,json=comicWorks,proto3" json:"comic_works,omitempty"`
}

func (x *ListComicWorkResponse) Reset() {
	*x = ListComicWorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_nft_v1_comic_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListComicWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComicWorkResponse) ProtoMessage() {}

func (x *ListComicWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_nft_v1_comic_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComicWorkResponse.ProtoReflect.Descriptor instead.
func (*ListComicWorkResponse) Descriptor() ([]byte, []int) {
	return file_api_nft_v1_comic_proto_rawDescGZIP(), []int{1}
}

func (x *ListComicWorkResponse) GetBaseListResponse() *v1.BaseListResponse {
	if x != nil {
		return x.BaseListResponse
	}
	return nil
}

func (x *ListComicWorkResponse) GetComicWorks() []*ComicWork {
	if x != nil {
		return x.ComicWorks
	}
	return nil
}

var File_api_nft_v1_comic_proto protoreflect.FileDescriptor

var file_api_nft_v1_comic_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x6e, 0x66, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d,
	0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x66,
	0x74, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x61, 0x70,
	0x69, 0x2f, 0x6e, 0x66, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x7a, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x69, 0x63,
	0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x11, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x0f, 0x62, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22,
	0x9c, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x69, 0x63, 0x57, 0x6f, 0x72,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x12, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x10, 0x62, 0x61, 0x73, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x69, 0x63, 0x5f,
	0x77, 0x6f, 0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x69, 0x63, 0x57, 0x6f,
	0x72, 0x6b, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x69, 0x63, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x42, 0x2b,
	0x0a, 0x0a, 0x61, 0x70, 0x69, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b,
	0x34, 0x63, 0x6c, 0x61, 0x62, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x6e, 0x66, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_nft_v1_comic_proto_rawDescOnce sync.Once
	file_api_nft_v1_comic_proto_rawDescData = file_api_nft_v1_comic_proto_rawDesc
)

func file_api_nft_v1_comic_proto_rawDescGZIP() []byte {
	file_api_nft_v1_comic_proto_rawDescOnce.Do(func() {
		file_api_nft_v1_comic_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_nft_v1_comic_proto_rawDescData)
	})
	return file_api_nft_v1_comic_proto_rawDescData
}

var file_api_nft_v1_comic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_nft_v1_comic_proto_goTypes = []interface{}{
	(*ListComicWorkRequest)(nil),  // 0: api.nft.v1.ListComicWorkRequest
	(*ListComicWorkResponse)(nil), // 1: api.nft.v1.ListComicWorkResponse
	(*v1.BaseListRequest)(nil),    // 2: api.base.v1.BaseListRequest
	(*v1.BaseListResponse)(nil),   // 3: api.base.v1.BaseListResponse
	(*ComicWork)(nil),             // 4: api.nft.v1.ComicWork
}
var file_api_nft_v1_comic_proto_depIdxs = []int32{
	2, // 0: api.nft.v1.ListComicWorkRequest.base_list_request:type_name -> api.base.v1.BaseListRequest
	3, // 1: api.nft.v1.ListComicWorkResponse.base_list_response:type_name -> api.base.v1.BaseListResponse
	4, // 2: api.nft.v1.ListComicWorkResponse.comic_works:type_name -> api.nft.v1.ComicWork
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_nft_v1_comic_proto_init() }
func file_api_nft_v1_comic_proto_init() {
	if File_api_nft_v1_comic_proto != nil {
		return
	}
	file_api_nft_v1_typs_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_nft_v1_comic_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListComicWorkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_nft_v1_comic_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListComicWorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_nft_v1_comic_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_nft_v1_comic_proto_goTypes,
		DependencyIndexes: file_api_nft_v1_comic_proto_depIdxs,
		MessageInfos:      file_api_nft_v1_comic_proto_msgTypes,
	}.Build()
	File_api_nft_v1_comic_proto = out.File
	file_api_nft_v1_comic_proto_rawDesc = nil
	file_api_nft_v1_comic_proto_goTypes = nil
	file_api_nft_v1_comic_proto_depIdxs = nil
}
