// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/auth/v1/auth.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on FetchSignMessageRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FetchSignMessageRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetAddress()) != 42 {
		return FetchSignMessageRequestValidationError{
			field:  "Address",
			reason: "value length must be 42 runes",
		}

	}

	return nil
}

// FetchSignMessageRequestValidationError is the validation error returned by
// FetchSignMessageRequest.Validate if the designated constraints aren't met.
type FetchSignMessageRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchSignMessageRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchSignMessageRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchSignMessageRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchSignMessageRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchSignMessageRequestValidationError) ErrorName() string {
	return "FetchSignMessageRequestValidationError"
}

// Error satisfies the builtin error interface
func (e FetchSignMessageRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchSignMessageRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchSignMessageRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchSignMessageRequestValidationError{}

// Validate checks the field values on FetchSignMessageResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *FetchSignMessageResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for SignMessage

	return nil
}

// FetchSignMessageResponseValidationError is the validation error returned by
// FetchSignMessageResponse.Validate if the designated constraints aren't met.
type FetchSignMessageResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FetchSignMessageResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FetchSignMessageResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FetchSignMessageResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FetchSignMessageResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FetchSignMessageResponseValidationError) ErrorName() string {
	return "FetchSignMessageResponseValidationError"
}

// Error satisfies the builtin error interface
func (e FetchSignMessageResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFetchSignMessageResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FetchSignMessageResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FetchSignMessageResponseValidationError{}

// Validate checks the field values on VerifySignToLoginSignRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifySignToLoginSignRequest) Validate() error {
	if m == nil {
		return nil
	}

	if utf8.RuneCountInString(m.GetAddress()) != 42 {
		return VerifySignToLoginSignRequestValidationError{
			field:  "Address",
			reason: "value length must be 42 runes",
		}

	}

	if utf8.RuneCountInString(m.GetMessage()) < 1 {
		return VerifySignToLoginSignRequestValidationError{
			field:  "Message",
			reason: "value length must be at least 1 runes",
		}
	}

	if utf8.RuneCountInString(m.GetSign()) < 1 {
		return VerifySignToLoginSignRequestValidationError{
			field:  "Sign",
			reason: "value length must be at least 1 runes",
		}
	}

	return nil
}

// VerifySignToLoginSignRequestValidationError is the validation error returned
// by VerifySignToLoginSignRequest.Validate if the designated constraints
// aren't met.
type VerifySignToLoginSignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifySignToLoginSignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifySignToLoginSignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifySignToLoginSignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifySignToLoginSignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifySignToLoginSignRequestValidationError) ErrorName() string {
	return "VerifySignToLoginSignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e VerifySignToLoginSignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifySignToLoginSignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifySignToLoginSignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifySignToLoginSignRequestValidationError{}

// Validate checks the field values on VerifySignToLoginSighResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *VerifySignToLoginSighResponse) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Token

	// no validation rules for Registered

	return nil
}

// VerifySignToLoginSighResponseValidationError is the validation error
// returned by VerifySignToLoginSighResponse.Validate if the designated
// constraints aren't met.
type VerifySignToLoginSighResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifySignToLoginSighResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifySignToLoginSighResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifySignToLoginSighResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifySignToLoginSighResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifySignToLoginSighResponseValidationError) ErrorName() string {
	return "VerifySignToLoginSighResponseValidationError"
}

// Error satisfies the builtin error interface
func (e VerifySignToLoginSighResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifySignToLoginSighResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifySignToLoginSighResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifySignToLoginSighResponseValidationError{}
