// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/tickets/v1/tickets.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CanMintRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CanMintRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CanMintRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CanMintRequestMultiError,
// or nil if none found.
func (m *CanMintRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CanMintRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Address

	if len(errors) > 0 {
		return CanMintRequestMultiError(errors)
	}
	return nil
}

// CanMintRequestMultiError is an error wrapping multiple validation errors
// returned by CanMintRequest.ValidateAll() if the designated constraints
// aren't met.
type CanMintRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CanMintRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CanMintRequestMultiError) AllErrors() []error { return m }

// CanMintRequestValidationError is the validation error returned by
// CanMintRequest.Validate if the designated constraints aren't met.
type CanMintRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CanMintRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CanMintRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CanMintRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CanMintRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CanMintRequestValidationError) ErrorName() string { return "CanMintRequestValidationError" }

// Error satisfies the builtin error interface
func (e CanMintRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCanMintRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CanMintRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CanMintRequestValidationError{}

// Validate checks the field values on CantMintResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CantMintResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CantMintResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CantMintResponseMultiError, or nil if none found.
func (m *CantMintResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CantMintResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for InWl

	// no validation rules for Level

	if len(errors) > 0 {
		return CantMintResponseMultiError(errors)
	}
	return nil
}

// CantMintResponseMultiError is an error wrapping multiple validation errors
// returned by CantMintResponse.ValidateAll() if the designated constraints
// aren't met.
type CantMintResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CantMintResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CantMintResponseMultiError) AllErrors() []error { return m }

// CantMintResponseValidationError is the validation error returned by
// CantMintResponse.Validate if the designated constraints aren't met.
type CantMintResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CantMintResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CantMintResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CantMintResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CantMintResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CantMintResponseValidationError) ErrorName() string { return "CantMintResponseValidationError" }

// Error satisfies the builtin error interface
func (e CantMintResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCantMintResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CantMintResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CantMintResponseValidationError{}
