// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"4clabs-server/app/contractlistener/internal/conf"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*ContractScriptApplication, func(), error) {
	contractScriptApplication := NewCronJobApplication(bootstrap)
	return contractScriptApplication, func() {
	}, nil
}
